import Head from 'next/head';
import Acceuil from '../container/Home/Home'
import Header from '../container/Layout/Header/Header'


export default function Home() {
  return (
    <>
      <Head>
        <title>Fil d'actualité | LinkedIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/linkedin.png" />
      </Head>
      <Header/>
      <br/>
      <br/>
      <br/>
      <Acceuil/>
    </>
  )
}
